//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapDaiSo
    {
        public System.DateTime NgayGioCap { get; set; }
        public string DichVu_ID { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<double> MaSoBatDau { get; set; }
        public Nullable<double> MaSoKetThuc { get; set; }
    
        public virtual DichVu DichVu { get; set; }
    }
}
