//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietChotDonHang
    {
        public Nullable<int> ChotDonHang_ID { get; set; }
        public string SoHieu { get; set; }
    
        public virtual ChotDonHang ChotDonHang { get; set; }
    }
}
