//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChotDonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChotDonHang()
        {
            this.ChiTietChotDonHang = new HashSet<ChiTietChotDonHang>();
        }
    
        public Nullable<System.DateTime> Ngay { get; set; }
        public string NguoiDung_ID { get; set; }
        public string NhanVien_ID { get; set; }
        public string KhachHang_ID { get; set; }
        public int ChotDonHang_ID { get; set; }
        public Nullable<System.DateTime> ThoiGianChotDonHang { get; set; }
        public string DonVi_ID { get; set; }
        public string TrangThaiChotDonHang { get; set; }
        public string TrangThaiXacNhanDonHang { get; set; }
        public Nullable<System.DateTime> ThoiGianXacNhanDonHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietChotDonHang> ChiTietChotDonHang { get; set; }
        public virtual DonVi DonVi { get; set; }
    }
}
