//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public string DonVi_ID { get; set; }
        public string NguoiDung_ID { get; set; }
        public string TenNguoiDung { get; set; }
        public string TenTruyCap { get; set; }
        public string MatKhau { get; set; }
        public string QuyenBuuDien_ID { get; set; }
    
        public virtual DonVi DonVi { get; set; }
        public virtual QuyenBuuDien QuyenBuuDien { get; set; }
    }
}
